### ISSUE TITLE
Livestreamer

### ISSUE THREAD

**Issue by freaktechnik** [freaktechnik/justintv-stream-notifications#108]
See livestreamer branch. Currently tries to use the child_process module, without success.

Other examples:
 - https://addons.mozilla.org/de/firefox/files/browse/301352/file/resources/livestreamer-launch-on-twitchtv/lib/main.js#top
 - https://github.com/Hunter5000/Twitch-Alarm/blob/master/twitch-alarm/lib/main.js

### TODO
 - [x] System detection stuff -> adjust path by OS
 - [x] Fix GTK missing on Linux.
 - [x] Context menu entry

**Comment by Nhoise** [comment]
Are you working on integrating livestreamer into your extension? That would be great.

Right click > open with Livestreamer. ![Kreygasm](https://static-cdn.jtvnw.net/emoticons/v1/41/1.0)

**Comment by freaktechnik** [comment]
And an option to always use livestreamer, yes.

**Comment by Nhoise** [comment]
What about quality selection? Afaik when not specifying a quality Livestreamer will auto pick Source/Best quality.
I prefer to have my streams run in medium.

**Comment by freaktechnik** [comment]
It currently uses about:config prefs for almost all configuration, but I can easily expose those as a preference (since those are also in about:config). It also has a preference for player selection and the path to livestreamer, if it doesn't work out of the box.

**Comment by Nhoise** [comment]
Very nice. Looking forward to the new updates.

**Comment by freaktechnik** [comment]
Merged to master. Released a new preview version on https://addons.mozilla.org/en-US/firefox/addon/justintv-stream-notificatio/versions/beta (needs at least Firefox 42)
